# Create Session

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "username": "douglas",
  "password": "123456"
}

### Create Product

POST http://localhost:3333/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NDA0NTc1ODcsImV4cCI6MTc0MDU0Mzk4Nywic3ViIjoiMSJ9.or5UfVKhkohkc0Tc3TcXDnuAn9m3baBz1E4VW3FDEtU

{
  "username": "douglas",
  "password": "123456"
}

### List Products
GET http://localhost:3333/products
