@baseUrl = http://localhost:3333

### Create Session
# @name login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "username": "douglas",
  "password": "123456"
}

### Create Product

POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "username": "douglas",
  "password": "123456"
}

### List Products
GET {{baseUrl}}/products